# Pyrefly configuration file
# This tells Pyrefly to use the project's virtual environment
# so it can resolve Django, DRF, Celery, etc.

python_interpreter = "C:\\Users\\singh\\Desktop\\Assignment\\.venv\\Scripts\\python.exe"

site_package_path = [
    "C:\\Users\\singh\\Desktop\\Assignment\\.venv\\Lib\\site-packages",
]

search_path = [
    "C:\\Users\\singh\\Desktop\\Assignment\\backend",
]
