# Generated by Django 6.0.5 on 2026-05-26 18:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap', 'SAP'), ('utility', 'Utility'), ('travel', 'Travel')], max_length=20)),
                ('file_name', models.CharField(max_length=500)),
                ('file_hash', models.CharField(blank=True, default='', help_text='SHA-256 for dedup detection', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_rows', models.IntegerField(blank=True, null=True)),
                ('parsed_rows', models.IntegerField(blank=True, null=True)),
                ('error_rows', models.IntegerField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('ingested_by', models.CharField(help_text='Email of uploader', max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='ingestion_files/')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL-safe identifier, e.g. acme-corp', max_length=100, unique=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitLookup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_unit', models.CharField(help_text='e.g. kWh, litres, MWh', max_length=30, unique=True)),
                ('factor_to_base', models.DecimalField(decimal_places=10, help_text='Multiplier to convert to base unit', max_digits=18)),
                ('base_unit', models.CharField(help_text='kWh for energy, km for distance, kg for mass', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(help_text='electricity | fuel | travel_air | travel_hotel | travel_ground', max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, default='', help_text='IN, GB, US-CA, etc.', max_length=100)),
                ('kg_co2e_per_unit', models.DecimalField(decimal_places=10, max_digits=18)),
                ('unit', models.CharField(help_text='The base unit this factor applies to', max_length=30)),
                ('year', models.IntegerField()),
                ('source_ref', models.CharField(blank=True, default='', help_text='e.g. DEFRA 2023, IEA 2023', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source_type', 'category', 'region', 'year'], name='core_emissi_source__09b742_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(help_text='scope_1 | scope_2 | scope_3', max_length=10)),
                ('category', models.CharField(help_text='e.g. fuel_combustion, business_travel_air', max_length=100)),
                ('source_type', models.CharField(max_length=20)),
                ('activity_date', models.DateField()),
                ('raw_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('raw_unit', models.CharField(help_text='e.g. litres, kWh, km', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('normalized_quantity_kg', models.DecimalField(blank=True, decimal_places=6, help_text='kg CO₂e', max_digits=18, null=True)),
                ('raw_payload', models.JSONField(help_text='Verbatim source row as JSON')),
                ('source_row_number', models.IntegerField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('flagged', 'Flagged'), ('locked', 'Locked')], default='pending', max_length=20)),
                ('flag_reason', models.TextField(blank=True, default='')),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, default='', max_length=255)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.emissionfactor')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.ingestionjob')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.tenant')),
                ('unit_lookup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unitlookup')),
            ],
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.tenant'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('changed_by', models.CharField(max_length=255)),
                ('action', models.CharField(help_text='created | edited | approved | flagged | locked', max_length=30)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.emissionrecord')),
            ],
            options={
                'ordering': ['changed_at'],
                'indexes': [models.Index(fields=['record', 'changed_at'], name='core_auditl_record__9a3bf2_idx')],
            },
        ),
        migrations.CreateModel(
            name='IngestionError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('raw_row', models.TextField(blank=True, default='', help_text='Original CSV row as string')),
                ('error_code', models.CharField(help_text='e.g. MISSING_DATE, UNKNOWN_UNIT', max_length=50)),
                ('error_message', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='core.ingestionjob')),
            ],
            options={
                'indexes': [models.Index(fields=['job'], name='core_ingest_job_id_cf595c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ingestionjob',
            index=models.Index(fields=['tenant', 'source_type'], name='core_ingest_tenant__e6cc87_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionjob',
            index=models.Index(fields=['tenant', 'status'], name='core_ingest_tenant__1f7ace_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'review_status'], name='core_emissi_tenant__af7a87_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'scope', 'activity_date'], name='core_emissi_tenant__0fa860_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['job'], name='core_emissi_job_id_c93050_idx'),
        ),
    ]
